# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20180321_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
