# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_blog_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
