# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0007_blog_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
                ('is_archieve', models.BooleanField(default=False, verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='categories.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
            ],
            options={
                'ordering': ('name', 'id'),
                'verbose_name': '\u0417\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
    ]
