# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='views_count',
        ),
    ]
