# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prescription',
            field=models.TextField(default='default', max_length=4096, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
