# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_auto_20180502_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='usertask',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438'),
        ),
    ]
